export default {
  dark: {
    backgroundDarker: '#010409',
    backgroundMain: '#0D1117',
    backgroundLighter: '#222B38',
    textMain: '#FFFFFF',
    textLight: '#C6C6C6',
    textButton: '#000000',
    textPlaceholder: '#3C4654',
    outline: '#222B38',
    success: '#1F9C8D',
    successLight: '#2EBBAA',
    danger: '#E02F44',
    dangerLight: '#E55466',
    button: '#DDDFE7',
    buttonLight: '#EAEAEA',
  },
  light: {
    backgroundDarker: '#EAEFF3',
    backgroundMain: '#F6F8FA',
    backgroundLighter: '#EAEFF3',
    textMain: '#000000',
    textLight: '#6C6C6C',
    textButton: '#000000',
    textPlaceholder: '#CCCFD3',
    outline: '#DDDFE7',
    success: '#1F9C8D',
    successLight: '#2EBBAA',
    danger: '#E02F44',
    dangerLight: '#E55466',
    button: '#BCBCBC',
    buttonLight: '#CBCBCB',
  },
};

// colors[isLightMode ? 'light' : 'dark'].backgroundMain
